name: Build ZMK firmware (nix)
on:
  workflow_dispatch:
  push:
    paths:
      - config/**
      - build.yaml

jobs:
  generate_zephyr_module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Folder and Copy Files
        run: |
          mkdir -p zephyr && cp .github/assets/zephyr-module.yml zephyr/module.yml
          ls zephyr
  build:
    uses: urob/zmk-actions/.github/workflows/build-user-config.yml@main
    with:
      # Set to 'gnuarmemb' 'zephyr' or 'zephyr-full' (from fastest to
      # most compatible). ZMK Studio requires 'zephyr-full'.
      toolchain: zephyr
